### ISSUE TITLE
Create *_index routes

### ISSUE THREAD

**Issue by vitorbaptista** [ckan/ckanext-pages#10]
We're using ```*_show``` routes with ```page=''``` as an index page route. Apart from being a bit confusing and not DRY (IMHO), I was unable to use ```h.build_nav_main``` to link to the blog's index, as I couldn't pass ```page=''``` to it.

I could've changed ```h.build_nav_main``` to allow passing parameters (and it might be a good idea in general) but, in this specific case, I think the correct fix is to add ```*_index``` routes.

The same pattern is used to create new pages. When using ```*_edit``` with ```page=''```, we go/create a new page.

@kindly What do you think? Is this pattern used in other places in CKAN? Looking quickly in ```ckan/config/routing.py```, I found a few routes like ```group_index``` and ```group_new```.

**Comment by metaodi** [comment]
I think this was solved with 5e2b989a14caaf08cc5b60e1946b646ac0f44fe5.
