### ISSUE TITLE
Support for ckan 2.9.2

### ISSUE THREAD

**Issue by turbatuandrei** [ckan/ckanext-pages#108]
After installing the module and starting ckan I get the following error:

ckan/lib/default/src/ckanext-pages/ckanext/pages/plugin.py", line 192, in get_actions
    'ckanext_pages_show': actions.pages_show,
AttributeError: module 'actions' has no attribute 'pages_show'

**Comment by amercader** [comment]
2.9 support is on the works. Should be ready at some point next week

**Comment by turbatuandrei** [comment]
Great, thanks!

**Comment by YukunYangNPF** [comment]
I'm also waiting for this. Hope it can be done soon!

**Comment by amercader** [comment]
Hey all, the `v0.3.0` tag includes support for CKAN 2.9 / Python 3. Please test and report any issues you find. Thanks.
