### ISSUE TITLE
Include HTML?

### ISSUE THREAD

**Issue by nathanwaters** [ckan/ckanext-pages#15]
How can I use regular HTML in the content area? Since the pages by default require sysadmin rights to create, it should be safe to accept HTML.

I found this, but not sure if it's usable: https://github.com/ckan/ckan/issues/1747

Simplest fix I found was to change {{ h.render_markdown(c.page.content) }} to {{ c.page.content|safe }} in page.html ...Markdown doesn't work when doing that, but html does

**Comment by tobes** [comment]
the fix for this is to change the template
    `{{ h.render_markdown(c.page.content) }}`
to
    `{{ h.render_markdown(c.page.content, allow_html=true) }}`
This should be made an option in the ckan config file or be selectable in the page creation IMHO

**Comment by metaodi** [comment]
Fixed with #19
