### ISSUE TITLE
Server Error - An internal server error occurred

### ISSUE THREAD

**Issue by yanik5** [ckan/ckanext-pages#23]
Any idea why your pages extension cause this https://gist.githubusercontent.com/wide-awake/e39b3b7ab9e006e43e83/raw/7ce8fc57b8287d2a905dbf560c7605fad0295ce4/error.log 

I add pages successfully, and they looks alright as a list but when i open full URL i got "Server Error An internal server error occurred" and above is apache2 ckan_default.error.log

answer from Zharktas: that would be broken python code in file controller.py since it uses varibale lxml before it has a value.

Your package is broken ?

**Comment by wide-awake** [comment]
Got it. I was missed out from lxml.
Install like this: 

apt-get install libxml2-dev libxslt1-dev python-dev
apt-get install python-lxml
