### ISSUE TITLE
Update pages

### ISSUE THREAD

**Issue by m1h** [ckan/ckanext-pages#24]
Hi, 

we are currently updating our ckan-version to 2.3.1. In this case we also have to update pages to the last version. However, we downloaded the last version and installed it via "python setup.py develop" (since there is no outgoing internet-connection on the remote server). Before the old folder was deleted and the new ckanext-pages-folder inserted. 

But: How is it ensured that text of already customized pages is not lost?

Kind regards!

**Comment by metaodi** [comment]
@m1h I know it's a little late for an answer, but the text you enter is independent from the code in the folder. The text is saved in the database and is not directly affected if the code is updated. Sometimes it might be needed to change the structure of the database, but these cases are rare and will be documented.

I'm closing this for now, but feel free to come back to this. I can re-open if necessary.
