### ISSUE TITLE
Markdown features

### ISSUE THREAD

**Issue by formwandler** [ckan/ckanext-pages#3]
Especially with this extension the usage of __Markdown__ becomes more important, since we can now create separate pages with it, which is really useful. Unfortunately, not all Markdown features about embedding __native HTML code__ work as described on the linked Markdown documentation. See CKAN issue [#1332](https://github.com/okfn/ckan/issues/1332).

So, a more "advanced" way to insert content - either as Markdown or integrated into the CKAN template framework - would really help.

**Comment by metaodi** [comment]
@formwandler this issue might be fixed with #19, as there is now a possibility to use "native" HTML. WDYT?

**Comment by formwandler** [comment]
@metaodi Does this mean that elements like `<img>` can be used in combination with Markdown like described in #1332 ? If so, this issue can be closed.

Unfortunately, I don't have CKAN >= 2.3 installed, so I can't test it right now.

**Comment by metaodi** [comment]
@formwandler yes, by enabling HTML you can use both Markdown and HTML. There is no limitation to certain tags, so everything is allowed (including potentially nasty stuff like `<script>`). But if you trust your users, this option can help you add more advanced content with ckanext-pages.

Therefore, I consider this issue fixed.

**Comment by formwandler** [comment]
Okay, great.

However, why do I need to trust "my users"? On my site only admins can edit those pages. I can't remember if I explicitly set permissions for this extension (or if this is possible at all). So, I just need to trust my admins, right?

**Comment by metaodi** [comment]
Yes that's correct. There might be CKAN instances, where people can register and then create pages. In those cases, you need to "trust" the users.
