### ISSUE TITLE
Create properly versioned releases

### ISSUE THREAD

**Issue by torfsen** [ckan/ckanext-pages#49]
Currently ckanext-pages doesn't have any [releases](https://github.com/ckan/ckanext-pages/releases), in fact it doesn't have any git tags at all. That makes it hard to pin a certain version of ckanext-pages as a dependency in automated CKAN installations. I could pin a certain commit, but that doesn't really tell me much half a year later -- I'd have to manually inspect all new commits to see what has changed.

Therefore, please start creating releases and version them via [semantic versioning](http://semver.org/).

**Comment by amercader** [comment]
@torfsen You should now have write access to this repo, feel free to tag / release / merge / etc as you see fit (obvs just ask any doubt). Just FYI @metaodi from Liip is also a maintainer. Thanks!

**Comment by torfsen** [comment]
Thanks! To get things going I will create a release using the current state as a baseline from which future changes can be tracked cleanly.

**Comment by torfsen** [comment]
I've created the [release 0.1.0](https://github.com/ckan/ckanext-pages/releases/tag/v0.1.0). From now on, changes should be tracked in [CHANGELOG.md](https://github.com/ckan/ckanext-pages/blob/master/CHANGELOG.md) using the conventions from [Keep a CHANGELOG](http://keepachangelog.com) and version numbers should follow [Semantic Versioning](http://semver.org/).
