### ISSUE TITLE
Travis build is broken

### ISSUE THREAD

**Issue by torfsen** [ckan/ckanext-pages#57]
The Travis CI build is broken, see for example [this build](https://travis-ci.org/ckan/ckanext-pages/jobs/273232432).

**Comment by torfsen** [comment]
The error message is:

    E: Version '1.2.2-1' for 'libcommons-fileupload-java' was not found

That version is also hard-coded in CKAN's current extension template, so if we figure out a fix here it should probably be ported there, too.

**Comment by amercader** [comment]
Yes, and we should use Travis' Postgres: https://github.com/ckan/ckanext-dcat/commit/6e5f9f788495268e036051714182947d78f49aab

**Comment by torfsen** [comment]
Fixed by #59.
