### ISSUE TITLE
Upgrade CKeditor to latest release

### ISSUE THREAD

**Issue by jqnatividad** [ckan/ckanext-pages#79]
The bundled version is 4.3.1 dating back to 2013 and the latest release is 4.10.

As a lot of installations are using ckanext-pages to create extensive documentation, we may also want to explore bundling the latest version with more ckeditor plugins - like the [full preset](https://ckeditor.com/cke4/presets), and adding [additional plugins like YouTube](https://ckeditor.com/cke4/addons/plugins/all?sort_by=field_custom_downloads_value&sort_order=DESC&page=0).

**Comment by amercader** [comment]
Done in `v0.3.0`. Please upgrade
